language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
env:
  - FLASK_APP=app.py FLASK_DEBUG=1
install:
  - pip install -r requirements.txt
  - mv config-example.py config.py
script: pytest