language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
env:
  - FLASK_APP=src/app.py FLASK_DEBUG=1
install:
  - pip install -r requirements.txt
  - mv src/config-example.py src/config.py
script: pytest src